version: '3.0'

services:
  graphql-crud-server-db:
    container_name: graphql-crud-server-db
    image: mongo:4.2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: graphql
      MONGO_INITDB_ROOT_PASSWORD: super-secret-password
#   ports:
#     - "27017-27019:27017-27019"
  graphql-crud-server:
    container_name: graphql-crud-server
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - graphql-crud-server-db
    ports:
      - "8080:8080"
    environment:
      SCHEMA_FILE: example/mongodb/schema/todo.graphql
      DATABASE_TYPE: MongoDB
      MONGODB_HOSTS: graphql-crud-server-db
      MONGODB_DATABASE: graphql
      MONGODB_USERNAME: graphql
      MONGODB_PASSWORD: super-secret-password